### PR TITLE
Midiplayer

### PR DESCRIPTION
**Pull request by ghost**
Fix: playback MIDI file with right tempo (only for fixed tempo).
I finally got it! 
:D

### CODE REVIEW

**Comment by vinniefalco** [comment]
Nice!!! But why did you remove the images? They are already in the
repository, removing them won't make the repo smaller...

Just wondering

On Wed, Apr 25, 2012 at 10:21 AM, SwingCoder
reply@reply.github.com
wrote:

> Fix: playback MIDI file with right tempo (only for fixed tempo).
> I finally got it!
> :D
> 
> You can merge this Pull Request by running:
> 
>  git pull https://github.com/SwingCoder/AppletJUCE midiplayer
> 
> Or you can view, comment on it, or merge it online at:
> 
>  https://github.com/vinniefalco/AppletJUCE/pull/2
> 
> -- Commit Summary --
> - Fix midiplayer to use sendBlockOfMessages()
> - change button's style and function playMidi() add a parameter(File&).
> - Fix: playback MIDI file with right tempo (only for fixed tempo).
> 
> -- File Changes --
> 
> D MIDIPlayer/BinaryData/about.gif (0)
> D MIDIPlayer/BinaryData/back.gif (0)
> D MIDIPlayer/BinaryData/icon.gif (0)
> D MIDIPlayer/BinaryData/open.gif (0)
> D MIDIPlayer/BinaryData/pause.gif (0)
> D MIDIPlayer/BinaryData/play.gif (0)
> D MIDIPlayer/BinaryData/setup.gif (0)
> M MIDIPlayer/Builds/MacOSX/Info.plist (2)
> M MIDIPlayer/Builds/MacOSX/MIDIPlayer.xcodeproj/project.pbxproj (30)
> M MIDIPlayer/Builds/VisualStudio2010/MIDIPlayer.vcxproj (5)
> M MIDIPlayer/Builds/VisualStudio2010/MIDIPlayer.vcxproj.filters (35)
> M MIDIPlayer/Builds/VisualStudio2010/icon.ico (0)
> M MIDIPlayer/Builds/VisualStudio2010/resources.rc (2)
> M MIDIPlayer/JuceLibraryCode/AppConfig.h (12)
> D MIDIPlayer/JuceLibraryCode/BinaryData.cpp (257)
> D MIDIPlayer/JuceLibraryCode/BinaryData.h (55)
> M MIDIPlayer/JuceLibraryCode/JuceHeader.h (1)
> M MIDIPlayer/MIDIPlayer.jucer (9)
> M MIDIPlayer/Source/ControlBar.cpp (94)
> M MIDIPlayer/Source/ControlBar.h (9)
> M MIDIPlayer/Source/MidiPlayer.cpp (108)
> M MIDIPlayer/Source/MidiPlayer.h (2)
> 
> -- Patch Links --
> 
>  https://github.com/vinniefalco/AppletJUCE/pull/2.patch
>  https://github.com/vinniefalco/AppletJUCE/pull/2.diff
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vinniefalco/AppletJUCE/pull/2

## 

Follow me on Github: https://github.com/vinniefalco

**Comment by ghost** [comment]
Before, using image button for familiar with GUI programming skill (how to use image etc.). Now, I have familiar with it.

In order to not fall into the GUI bad marshes, I think that my main learning content shouldn't on GUI, therefore remove these image data.

The current focus is MIDI playback things. a lot of things need solved. I would like first to perfected MidiPlayer class, so the future can reuse and avoid duplication write same code. Just like Tic-Tac-Toe's SoundPlayer class.

:)

**Comment by vinniefalco** [comment]
Actually, I liked the image buttons...they looked nice !!

On Wed, Apr 25, 2012 at 10:41 AM, SwingCoder
reply@reply.github.com
wrote:

> Before, using image button for familiar with GUI programming skill (how to use image etc.). Now, I have familiar with it.
> 
> In order to not fall into the GUI bad marshes, I think that my main learning content shouldn't on GUI, therefore remove these image data.
> 
> The current focus is MIDI playback things. a lot of things need solved. I would like first to perfected MidiPlayer class, so the future can reuse and avoid duplication write same code. Just like Tic-Tac-Toe's SoundPlayer class.
> 
> :)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vinniefalco/AppletJUCE/pull/2#issuecomment-5337314

## 

Follow me on Github: https://github.com/vinniefalco

**Comment by ghost** [comment]
A little piece of cake, no problem.
I'll re-use them.

**Comment by vinniefalco** [comment]
Did you draw those images?

On Wed, Apr 25, 2012 at 10:47 AM, SwingCoder
reply@reply.github.com
wrote:

> A little piece of cake, no problem.
> I'll re-use them.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vinniefalco/AppletJUCE/pull/2#issuecomment-5337450

## 

Follow me on Github: https://github.com/vinniefalco

**Comment by ghost** [comment]
I can draw better than them.

They are just some free icons, I downloaded from the Internet. In my opinion, they are so ugly.

:D

**Comment by vinniefalco** [comment]
Any chance you could amend the commit? You would have to roll back the
last 2 commits in your local branch by using "git reset" (read the
docs for the proper options), then adjusting your sources to keep the
images. After you finish replacing the commits you would use git push
--force to update the midiplayer branch in your remote, that will
automatically update the pull request.

let me know if you want to try this. If not, you can just put fresh
commits on top of the existing two that bring the images back. Or if
you want, we can just remove the images. But they will still be in the
repository (since they are part of history).

What would you like to do?

**Comment by ghost** [comment]
I want to focus on MidiPlayer class, instead of the GUI image programming. too many things need solve...My brain is not enough...

Git is always the simple things get too complex, not suitable for the beginners of the stages of learning.

I really don‘t like Git. also can’t adapt "network communication" to learn something...

These are not debate, just express my true thoughts...

**Pull request closed without merging**
